

# Indica el lenguaje a usar
language: java

# Especifica la version de jdk
jdk:
    - openjdk8
    - openjdk10
    - openjdk11
    - oraclejdk11

# Especifica el SO y la distribución a usar
arch: amd64
os: linux
dist: xenial

# Ejecuta el test
script:
    - gradle test